### ISSUE TITLE
correction to docs: import statement

### ISSUE THREAD

**Issue by DavidODonovan** [vasturiano/d3-radial-axis#1]
Hi! Your docs for import are slightly incorrect. 
They say;  import { d3AxisRadialInner, d3AxisRadialOuter } from 'd3-radial-axis';
Should be: import { axisRadialInner, axisRadialOuter } from 'd3-radial-axis';

Thanks!

**Comment by vasturiano** [comment]
Thanks @DavidODonovan, fixed!
