### ISSUE TITLE
Not working in Angular 16, TS 5.0.2 and file missing in npm

### ISSUE THREAD

**Issue by abinovarghese** [vasturiano/d3-radial-axis#5]
the js file is missing in the published npm repository. We can only see index.js file
![image](https://github.com/vasturiano/d3-radial-axis/assets/9087797/1dfa4e0c-dfbb-4403-830c-2598ad079c24)

**Comment by vasturiano** [comment]
Thanks for the heads up @abinovarghese! This is now fixed in `v1.8.0`, and you should find the ES module binding files in NPM from this version on.
